# obstacle_range: 5
# raytrace_range: 5
# footprint: [[0.9, 0.3], [0.9, -0.3], [-0.3, -0.3], [-0.3, 0.3]]
# map_topic: /map
# subscribe_to_update: true
# observation_sources: laser_scan_sensor
# laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true , clearing: true }
# global_frame: map
# robot_base_frame: base_link
# always_send_full_costmap: true


# obstacle_range: 5.0
# raytrace_range: 5.0
# footprint: [[0.5, 0.3], [0.5, -0.3], [-0.3, -0.3], [-0.3, 0.3]]
# map_topic: /map
# subscribe_to_update: true
# observation_sources: laser_scan_sensor
# laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true , clearing: true }
# global_frame: map
# robot_base_frame: base_link
# always_send_full_costmap: true


obstacle_range: 3.0
raytrace_range: 3.5
footprint: [[-0.25, -0.375], [-0.25, 0.375], [0.25, 0.375], [0.25, -0.375]]
#robot_radius: 0.105

inflation_radius: 1
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: rplidar, data_type: LaserScan, topic: scan, marking: true, clearing: true}
#depth_camera: {sensor_frame: d435_depth_frame, data_type: PointCloud2, topic: rtabmap/cloud_map, marking: true, clearing: true}